import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { Providers } from "../providers";
import { Header } from "@/components/layout/layout/header";
import { Footer } from "@/components/layout/layout/footer.component";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "egypt ip exchange",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{
    locale: string; // Added type for locale
  }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div
          className={
            "flex h-auto w-screen flex-col overflow-x-hidden min-h-screen"
          }
        >
          <Providers locale={locale}>
            <div className="flex w-full flex-col items-center bg-headerColor">
              <div className="container overflow-hidden py-8 ">
                <Header />
              </div>
            </div>

            <div className="flex w-full flex-1 flex-col   justify-center bg-white h-screen">
              {children}
            </div>

            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  );
}
